---
builds:
  - main: ./cmd/ach/main.go
    binary: ach
    ldflags:
      - "-X github.com.yuchiki.atcoderHelper/internal/cmd/ach/version.version=\
        {{.Version}}"
      - "-X github.com.yuchiki.atcoderHelper/internal/cmd/ach/version.commit=\
        {{.Commit}}"
      - "-X github.com.yuchiki.atcoderHelper/internal/cmd/ach/version.edited=''"
      - "-X github.com.yuchiki.atcoderHelper/internal/cmd/ach/version.date=\
        {{.Date}}"
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  -
    format: zip
release:
  prerelease: auto
