default-strategy-and-os: &default-strategy-and-os
  strategy:
    matrix:
      os: [ ubuntu-latest, macos-latest]
  run-on: {{matrix.os}}

name: golang-ci
on:
  push:
    tags:
      - v+
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    <<: +default-strategy-and-os
    steps:
    - uses: actions/checkout@v2
    - name: enable problem matcher
      run: echo "::add-matcher::.github/go-test-problem-matcher.json"
    - name: test
      uses: cedrickring/golang-action/go1.14@1.6.0
      with:
        args: go build ./...
  test:
    name: test
    <<: *default-strategy-and-os
    steps:
    - uses: actions/checkout@v2
    - name: enable problem matcher
      run: echo "::add-matcher::.github/go-test-problem-matcher.json"
    - name: test
      uses: cedrickring/golang-action/go1.14@1.6.0
      with:
        args: go test ./...
  lint:
    name: lint
    <<: *default-strategy-and-os
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
