name: golang-ci
on: [push, pull_request]
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: enable problem matcher
      run: echo "::add-matcher::.github/go-test-problem-matcher.json"
    - name: test
      uses: cedrickring/golang-action/go1.14@1.6.0
      with:
        args: make test
    - name: detect format diff
      run: git diff --exit-code
