---
name: golang-ci
on:
  push:
    tags:
      - v+
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: enable problem matcher
        run: echo "::add-matcher::.github/go-test-problem-matcher.json"
      - name: test
        uses: cedrickring/golang-action/go1.14@1.6.0
        with:
          args: go build ./...
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: enable problem matcher
        run: echo "::add-matcher::.github/go-test-problem-matcher.json"
      - name: test
        uses: cedrickring/golang-action/go1.14@1.6.0
        with:
          args: go test ./...
  lint:
    name: lint
    runs-on: ubuntu-latest # lintはコードの問題なので、意図的に1環境でしかテストしない
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  yamllint:
    name: yamllint
    run-on: ubuntu-latest # lintはコードの問題なので、意図的に1環境でしかテストしない
    steps:
      - actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
