---
name: release
on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types:
      - ci-passed
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: ${{ startsWith(gighub.event.client_payload.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: notify to discord
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          description: ${{ steps.create-send-message.outputs.message }}
