---
name: release
on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types:
      - ci-passed
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.client_payload.ref, 'refs/tags/') }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  notification:
    name: notification
    if: always()
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: set send message
        id: create-send-message
        run: |
          if [ ${{env.WORKFLOW_CONCLUSION}} != success ]; then
            echo -n "::set-output name=message::"
            echo -n "<@${{secrets.DISCORD_NOTIFICATION_ID}}>"
          fi
      - name: notify to discord
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          description: ${{ steps.create-send-message.outputs.message }}
